### ISSUE TITLE
Bug - error filtering by # of findings 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#104]
## steps to reproduce the bug.

1. Selected "Dept of Transportation" from dropdown, 
2. Clicked on "Only show audits with findings" and "Include audits with findings for specified agency"
3. Clicked on "findings count" to sort by least to greatest # 
4. Clicked on "findings count" again 
5. Returns "502 Bad Gateway: Registered endpoint failed to handle the request."

### Desired update 
Step 5 above should sort findings by greatest # to least #

**Comment by danielnaab** [comment]
You'll get a 502 if a request takes too long to complete, which, given our resource constraints, might happen with large search results.

There have been some changes that will speed up some queries so hopefully it is less common.

**Comment by bpdesigns** [comment]
Thanks @danielnaab is there a way to estimate when this will happen - such as size of result? 

Can we create a custom 502 response explaining what's happening?

**Comment by danielnaab** [comment]
@bpdesigns not sure on estimates, but yes we can likely create a custom error message.

**Comment by bpdesigns** [comment]
Thanks Dan, how about: 

"Sorry for this 502 response. Our prototype system cannot handle this size of a search at the moment due to resource constraints. Please try another search and if this problem persists contact: federal-grant-reporting@gsa.gov and we'll work to resolve it. 

Thanks for using Distiller!"

**Comment by bpdesigns** [comment]
This is a cloud.gov issue that we don't control
