### ISSUE TITLE
Search page column details updated 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#106]
Current Column arrangement (left to right) 
- Auditee name 
- Fiscal year end
- Audit accepted
- Findings count 
- Cog/oversight agency
- Questioned costs 
- Amount expended by selected agency
- Files

Update Column arrangement (left to right) 
- [x] Auditee name 
- [x] Fiscal year end
- [x] Audit accepted
- [x] Findings count 
- [x] Repeat findings (add)
- [x] Questioned costs (moved left)
- [x] Cog/oversight agency
- [x] Amount expended by selected agency
- [x] Files

Description update
- [x] Change the "Amount expended by selected agency" column to "Amount expended by parent agency for fiscal year"

**Comment by danielnaab** [comment]
@bpdesigns Repeat findings has proven to be difficult to add to search results with an acceptable query time, so it has been added as an unsortable value.
