### ISSUE TITLE
update UI header 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#109]
## User story

As a visitor to Distiller, I want know where the data is from and when its updated so that I know it's trustworthy.

## Acceptance criteria
- [x] add "last updated: "DD/MM/YY" and left align it to the dropdown list. 
- [x] scale down logo and right align it to the dropdown list

Text updates
- [x] add this description text to the right side of centered dropdowns
"Distiller combines data from beta.sam.gov and the Federal Audit Clearinghouse to give you quick access to single audit information."
- [x] below that text block lets add an email contact that says - "Let us know if Distiller helped make your better or if you have suggestions at federal-grant-reporting@gsa.gov."

- [x] underline the text "Distiller" make it black and create a hyperlink to "https://github.com/18F/FAC-Distiller"
- [x] note in the two images below that the block of description text is left aligned but the right hand rag adjusts to the width of the page. The two images below indicate the narrowest and widest length of text.

narrow right side text column
<img width="748" alt="Screen Shot 2020-02-25 at 6 27 24 PM" src="https://user-images.githubusercontent.com/15329140/75298841-8baffe80-5801-11ea-8374-36be14dd1b3b.png">

widest right side text column
<img width="1079" alt="Screen Shot 2020-02-25 at 6 27 46 PM" src="https://user-images.githubusercontent.com/15329140/75298913-b601bc00-5801-11ea-88dd-a67bf888e149.png">

## Implementation notes
@danielnaab I imagine the description text block might be funky to implement. Let me know if you have questions.

**Comment by bpdesigns** [comment]
If viewed on Mobile lets stack the text from the upper right at the top of the page

**Comment by danielnaab** [comment]
@bpdesigns The sidebar text was a bit tricky with the way the page is currently laid out... What I came up with isn't perfect but I think it gets the core of what you're going for.
