### ISSUE TITLE
Set up initial deployment to cloud.gov

### ISSUE THREAD

**Issue by fureigh** [18F/FAC-Distiller#24]
## User story
As a person invested in this project's future, I want to set up deployment to cloud.gov so that the prototype is easier to demo and explore.

## Acceptance criteria
- [x] The single audit findings resolution prototype is accessible on cloud.gov.

## Outstanding questions
- At some point: which other pieces should be made accessible, and how?

## Implementation notes
- Start with a sandbox; check into other options.
- Guard against the possibility of any PII being entered.

**Comment by danielnaab** [comment]
The deployment is live with a test db populated; there will be follow-up work required to the cloud.gov environment to add an S3 bucket for the various data sources.

**Comment by bpdesigns** [comment]
Closing with follow up work on #29 Add an S3 bucket for the various data sources to cloud.gov deployment
