### ISSUE TITLE
UI when Distiller returns results 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#27]
We want to keep the dropdowns at the top if the page and return a table of results that includes:

- [x] - Grantee name
- [x] - Audit # - and maybe here we include links to download the audit [Form] and [PDF]
- [x] - Finding #s 
- [x] - repeat findings # (if no repeat findings enter "N/A")
- [x] - cognizant or oversight agency for the finding
- [x] - Findings text (show the first part of it and have a button to expand the text) - and a download text link
- [x] - Corrective action plan text (CAP) (show the first part of it and have a button to expand the text) - and a download text link

**Comment by bpdesigns** [comment]
Link to download data as a CSV

**Comment by bpdesigns** [comment]
@bpdesigns to Investigate how to display inline text with USWDS

**Comment by bpdesigns** [comment]
@danielnaab For the styling of the text for the findings text - from the uswds paragraph styles [page] (https://designsystem.digital.gov/utilities/paragraph-styles/) lets use [.measure-2] and [.line-height-sans-6] the font in the example is source sans pro, but I think we could use Public sans.

**Comment by bpdesigns** [comment]
![finding details ui](https://user-images.githubusercontent.com/15329140/72570670-828b5380-388b-11ea-937f-ec1e267c934a.jpg)

![finding details ui](https://user-images.githubusercontent.com/15329140/72570680-87500780-388b-11ea-96a5-3beb7aa41e84.jpg)

**Comment by bpdesigns** [comment]
@danielnaab initial wireframes for presenting distiller data. ... On reflection, I need to update how the links would work from these pages, but I think can give you a sense of what I thinking.

**Comment by danielnaab** [comment]
Looks good! Would the findings details be grouped by audit number?

**Comment by bpdesigns** [comment]
@danielnaab FYI - I updated the above screenshots with a second tab of content. 

Yes - I would group findings by audit #

**Comment by bpdesigns** [comment]
@danielnaab will have an update with a chance to how things link and download hopefully by this afternoon. Also, I updated the first comment in this thread with the most important data we want to show. Things like "DBKEY" would be a nice to have as added context but not essential content. I'm still thinking about the order of the columns.

**Comment by bpdesigns** [comment]
@danielnaab In the case that we return a lot of results (like 100 +) my initial though is show all the  results on one page with a vertical scroll so you see 20 results at a time within a window. -  Let me know if that interaction idea is clear.

**Comment by danielnaab** [comment]
Here's where things are with in-progress work
![image](https://user-images.githubusercontent.com/136512/72821293-efa93b00-3c35-11ea-8d5a-88a1529696df.png)

**Comment by bpdesigns** [comment]
Hi @danielnaab here is a UI update. Just moved around the top filters

<img width="826" alt="Screen Shot 2020-01-21 at 3 45 48 PM" src="https://user-images.githubusercontent.com/15329140/72841957-6f023300-3c65-11ea-93cb-5bb74ef40d3c.png">

**Comment by bpdesigns** [comment]
![search results  ui 013020](https://user-images.githubusercontent.com/15329140/73487187-7b2c7580-4374-11ea-84a7-38fc9ca27717.jpg)

**Comment by bpdesigns** [comment]
Hi @danielnaab here is the page to show findings. Let me know if you have any questions. I moved a few things around. Thanks

![Distiller ui 013120](https://user-images.githubusercontent.com/15329140/73554048-05c6b080-4419-11ea-8671-1da46b74b6ad.jpg)
