### ISSUE TITLE
Shore up ETLs - General, CFDA, Findings, Findings Text

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#30]
Acceptance Criteria
- [x] ETLs being stable - prepped to run in cloud.gov
- [x] Document (add a wiki page) with the ways that the data is creating constraints.

**Comment by danielnaab** [comment]
- Some notes on the ETLs here: https://github.com/18F/FAC-Distiller/wiki/Single-Audit-Data-Sources
- See the README for instructions on how to run the jobs locally.
- #37 (on-going) will deal with running on deployed environment
