### ISSUE TITLE
As a dev I want to be able to access s3 pdf data

### ISSUE THREAD

**Issue by cantsin** [18F/FAC-Distiller#40]
## User story

As a dev, I want retrieved pdfs in s3 so that we can do textual analysis on these files.

## Acceptance criteria

- [ ] We know which pdfs correspond to which single audits
- [ ] We can access the given s3 bucket from outside for testing purposes (https://cloud.gov/docs/services/s3/#interacting-with-your-s3-bucket-from-outside-cloud-gov)

## Outstanding questions

- How the pdf/s3 mapping works currently vis a vis how it should work (DBKEY/Audit Year)? 
- Should we be renaming the pdf files?

**Comment by bpdesigns** [comment]
So based on our conversation today its sounds like we're gonna approach this a different way. 

Gonna close this. @cantsin please reopen it if there are things here still worth referencing.
