### ISSUE TITLE
IE compatibility issues 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#49]
## User story

As a government employee, I want the distiller to work on a PC running old versions of IE so that I can use all the features of the distiller 

## Acceptance criteria

- [x] "Findings count" link opens the findings text page
- [x] Audit accepted "to" and "from" dates show the "dd/mm/yyyy" to indicate the text that needs to be filled 

## Outstanding questions

- _not sure if there are more issues and what version of IE our usability tester was using _

**Comment by bpdesigns** [comment]
@danielnaab I tried this on a virtual PC and it didn't work for me. It could just be the virtual machine...

**Comment by danielnaab** [comment]
@bpdesigns sorry, I haven't deployed it yet; I've got a crawl job running, and deploying would kill it. I'll let you know when the deployment is updated.

**Comment by bpdesigns** [comment]
Ah! No Worries :)


On Feb 11, 2020, at 5:15 PM, Daniel Naab <notifications@github.com> wrote:

﻿

@bpdesigns <https://github.com/bpdesigns> sorry, I haven't deployed it yet;
I've got a crawl job running, and deploying would kill it. I'll let you
know when the deployment is updated.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/FAC-Distiller/issues/49?email_source=notifications&email_token=ADU6O5DU4LVK5X2DSFZT75LRCMPQJA5CNFSM4KP7EAB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELOJULY#issuecomment-584882735>,
or unsubscribe
