### ISSUE TITLE
Add options to filter by cog/oversight

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#50]
## User story

Some agency users want to see all audits related to their agency, some of the searches that are also useful to them are to filter by cog/oversight 

## Acceptance criteria

- [ ] checkboxes for "Cognizant/Oversight" and "Non Cognizant/Oversight"

## Implementation notes

- [ ] see uswds checkboxes for implementation
- [ ] have both boxes checked by default

<img width="401" alt="Screen Shot 2020-02-04 at 4 38 05 PM" src="https://user-images.githubusercontent.com/15329140/73794052-31c19900-476d-11ea-951d-c9844b4807e8.png">

**Comment by danielnaab** [comment]
Looking into this one now - there's a catch I'd like to point out.

Currently, the search results are "all audits that have findings associated with agency CFDA `XX.YYYY`". Cog/oversight would change it to a simpler query, of "audits that have a CFDA cog/oversight prefix of `XX`".

I'm not certain how to make that distinction clear in the UI. Thoughts?

**Comment by danielnaab** [comment]
I'll hold off on deploying this until a large crawl is complete

**Comment by bpdesigns** [comment]
@danielnaab lets chat about this in stand.
