### ISSUE TITLE
As a developer, I would like to automate cloud.gov deployment

### ISSUE THREAD

**Issue by cantsin** [18F/FAC-Distiller#54]
## User story

As a developer, I want to automate cloud.gov deployment so that anyone else can take over the work and deploy to their own instance. Additionally, we may need to scale up as memory/CPU requirements become more demanding.

## Acceptance criteria

- [x] A shell script of `cf` commands
- [x] Updated README

## Outstanding questions

None

## Implementation notes

None

**Comment by bpdesigns** [comment]
@cantsin what do we need to do so that people visiting the github repo understand whats in it and how to use it from a technical point of view. and what do ypou think about making a new repo for just this work? might make it more clear. thoughts?

**Comment by bpdesigns** [comment]
I can create a new repo after you create the documentation

**Comment by cantsin** [comment]
Yes, the deployment script will have documentation: the purpose of this script is to ensure any interested party can deploy FAC-distiller on their own cloud.gov instance. Not sure where a new repo comes in here -- can you clarify, please?

**Comment by bpdesigns** [comment]
Yes. you are right, we don't need a new repo
