### ISSUE TITLE
Dropdown refinement

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#58]
### current
when there is no subagency the subagency dropdown is still active but contains no data

### update
- when there is no subagency associated with an agency deactivate the subagency dropdown

**Comment by danielnaab** [comment]
This should already be done, but there is some confusion in the circumstance where there is a single sub-agency. For example, the National Credit Union Administration has one "sub-agency" (itself), but Inter-American Foundation has none. You want to also disable when there's one option?

**Comment by bpdesigns** [comment]
If there is NO subagency lets disable it. 

If there is one subagency lets keep it as is. I'm not sure we can count on it being one to one - unless you can tell thats the case - then we can disable it for that use case as well
