### ISSUE TITLE
table spacing 

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#62]
- [ ]  widen the table on both the search and findings pages by 100px
- [ ] make width of the column for the findings text and the corrective action plan the same width.

**Comment by bpdesigns** [comment]
I think we hacked this in standup. I'll wait for @danielnaab to give the OK and I'll close this ticket.

**Comment by danielnaab** [comment]
@bpdesigns There's still work to make the changes in the code

**Comment by bpdesigns** [comment]
yep. Imagined that was the case.
