### ISSUE TITLE
link styling for findings content

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#63]
## Acceptance criteria

- [x] remove the paperclip and arrow icons for the "copy," "expand," and "contract" actions on the findings page and replace with text links (styling below)
- [x] show only 5 rows of text for findings by default  

<img width="882" alt="Screen Shot 2020-02-11 at 11 41 03 AM" src="https://user-images.githubusercontent.com/15329140/74258019-a479c980-4cc3-11ea-9d0d-996ee96db5a5.png">

 ## Implementation notes 
- the following is for the "findings text" column. This is the column that we'll have the "expand" and "hide text" feature. 
 - for the "corrective action text" column add a copy button 
- "copy text" button should copy only the text in the specified cell. 
- the "..." should come at the end of the last row of text in the collapsed state. 
- the "..." should come after the last full word that can fit on the line if thats easy enough to do
- the  "expand," "hide text," and "copy" links should all be flush right to the bottom of the cell they exist in.

#### active state
<img width="242" alt="Screen Shot 2020-02-11 at 11 47 25 AM" src="https://user-images.githubusercontent.com/15329140/74258588-94aeb500-4cc4-11ea-9641-2d2879e35aa2.png">
#### text copied state
<img width="241" alt="Screen Shot 2020-02-11 at 11 47 34 AM" src="https://user-images.githubusercontent.com/15329140/74258598-9a0bff80-4cc4-11ea-8f7b-8569d467754a.png">
#### expanded text state
<img width="242" alt="Screen Shot 2020-02-11 at 11 47 42 AM" src="https://user-images.githubusercontent.com/15329140/74258622-a55f2b00-4cc4-11ea-9a3b-b4b45b6581c5.png">

**Comment by danielnaab** [comment]
@bpdesigns any of the 3 columns (including CFDA #) might be more than 5 rows of text - should we put the links in the finding column instead, or duplicate expand/collapse links in each of the three cells?

The problem with duplicating it is the max height should apply to the whole row, not just the cell.

![image](https://user-images.githubusercontent.com/136512/74853593-c1398100-5303-11ea-8d22-fc2cac078816.png)

**Comment by bpdesigns** [comment]
- [ ] Add the "copy/ expand" to the "corrective action plan" column as well
- [ ] "CFDA awards" column do not add copy/ expand." If "CFDA awards" cell has text hidden by the limited view of lines of text that is okay. Lets indicate with three dots  ". . . "  in the last line where there is text hidden. 

Let me know if this is clear @danielnaab

**Comment by danielnaab** [comment]
Hope this is an okay alternative... Due to browser compatibility issues and a desire to not add additional third-party Javascript dependencies, I used a faded line to indicate clipped text rather than an ellipsis.

![image](https://user-images.githubusercontent.com/136512/75053084-4b195380-5496-11ea-801e-5b9be776f6e7.png)

**Comment by bpdesigns** [comment]
Thanks @danielnaab, that works. 

One update based on this screenshot - lets underline the expand link.
