### ISSUE TITLE
migrate to the gsa-10x-prototyping cloud.gov org

### ISSUE THREAD

**Issue by cantsin** [18F/FAC-Distiller#72]
## User story

As a dev, I want to migrate to the `gsa-10x-prototyping` org so that the FAC distiller isn't cleared when the sandbox 90 days limit is up.

## Acceptance criteria

- [x] Set up a new app in the `gsa-10x-prototyping` with an official URL

## Outstanding questions

- What should the new demo url look like? `https://demo-fac-distiller.app.cloud.gov/` ?

## Implementation notes

Depends on https://github.com/18F/FAC-Distiller/issues/54

**Comment by cantsin** [comment]
@danielnaab FYI. also @bpdesigns OK with the proposed demo url above?

**Comment by bpdesigns** [comment]
@cantsin Yes that URL makes sense.

**Comment by cantsin** [comment]
http://demo-fac-distiller.app.cloud.gov/ is up, but I will make a separate issue for migration.
