### ISSUE TITLE
If the FAC says the search returned too many results, automatically run smaller subsearches

### ISSUE THREAD

**Issue by fureigh** [18F/FAC-Distiller#8]
## User story
As a user, I want Distiller to handle resubmitting smaller requests and troubleshooting which ones will be small enough to get through so that I 1) can get all of the files for which I'm searching and 2) don't have to do that guess-and-checkwork myself. 

## Acceptance criteria
- [ ] TK
- [ ]
- [ ]

## Outstanding questions
- _(if applicable)_

## Implementation notes
Minimum viable fallback plan would be presenting a clear next step in the user's actual browser. But knocking this one out would spare an awful lot of hassle.

**Comment by bpdesigns** [comment]
Unclear if this is going to be an issue if we're creating our own database
