### ISSUE TITLE
UI tweaks to column header

### ISSUE THREAD

**Issue by bpdesigns** [18F/FAC-Distiller#94]
- [x] change the text in the column headers to black
- [x] add numerical sort by # of findings 
- [x] change the "Amount expended" to read "amount expended by selected agency" and only show the amount of money expended by that agency instead of expended by all agencies

**Comment by danielnaab** [comment]
> * [ ]  change the "Amount expended" to read "amount expended by selected agency" and only show the amount of money expended by that agency instead of expended by all agencies

@bpdesigns Making this query with the Django ORM and the third-party `django-composite-key` library we're using is proving to be difficult; there appears to be a bug in the interaction between the two, so I'm currently not able to efficiently query for this over the CFDA table. I could calculate this in code instead, but it wouldn't be sortable. Would that be suitable, or should I invest more time in this?

**Comment by bpdesigns** [comment]
sounds good @danielnaab
